### ISSUE TITLE
Should this depend on work queued

### ISSUE THREAD

**Issue by bonnyr** [weberr13/go-reducers#3]
https://github.com/weberr13/go-reducers/blob/31d27f052ed342d46dcdb051fc36fcacb7d52236/mapping/mapping.go#L40

**Comment by bonnyr** [comment]
I wonder if this should in some way depend on the amount of work queued rather than creating a fixed number of goroutines, although cheap, still have to be scheduled for execution and check channel state before completing

**Comment by weberr13** [comment]
Because the work queue is a channel modeling the concept of a lazy sequence this sort of optimization is not possible.  I am intentionally using a static thread pool to match the methodology used in r/reducers in clojure.  This is also why an identity constructor is required as in cases where there are very small workloads (like the unit tests) you end up with a number of workers that get no work and close by putting an identity object on the stack.  Although there is some overhead in using lazy sequences rather than vectors of known sizes the benefits in the long run should outweigh the overhead of extra folds with small data sets.
